$ErrorActionPreference='Stop'
$raw='D:\TRADING SYSTEM\02_CURRENT_HISTORICAL_RAW_DATA_UJI\Raw Des 02-31-2024.csv'
$date='2024-12-02'
$md5='b8d42b35c90d2dff8b18ae4e1734523b'
$sha='5bddb43f243e3cbb76504ecc38d8b0981e38866b7a4ea3b4557dcbbf3024712c'
if(-not(Test-Path -LiteralPath $raw -PathType Leaf)){throw 'RAW_MISSING'}
$gm=(Get-FileHash -LiteralPath $raw -Algorithm MD5).Hash.ToLowerInvariant();$gs=(Get-FileHash -LiteralPath $raw -Algorithm SHA256).Hash.ToLowerInvariant();if($gm-ne$md5-or$gs-ne$sha){throw 'RAW_HASH_MISMATCH'}
$out=Join-Path $PWD 'machine1_next_621_630_20241202_evidence';New-Item -ItemType Directory -Path $out -Force|Out-Null
# Pass 1: deterministically rebuild the complete 2024-12-02 ticker manifest from canonical raw source.
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576)
try{$hdr=$sr.ReadLine();$h=@($hdr.TrimStart([char]0xFEFF).Split(','));$ti=[Array]::IndexOf($h,'RAW_TICKER');$di=[Array]::IndexOf($h,'RAW_DATETIME_ISO');if($ti-lt0-or$di-lt0){throw 'HEADER'};$agg=@{};$row=0;while(-not$sr.EndOfStream){$line=$sr.ReadLine();$row++;$f=$line.Split(',');if($f.Count-le[Math]::Max($ti,$di)){continue};$dt=$f[$di].Trim('"');if(-not$dt.StartsWith($date)){continue};$t=$f[$ti].Trim('"');if(-not$agg.ContainsKey($t)){$agg[$t]=[ordered]@{ticker=$t;first=$row;last=$row;count=1;first_datetime=$dt;last_datetime=$dt}}else{$a=$agg[$t];$a.last=$row;$a.count++;$a.last_datetime=$dt}}}finally{$sr.Dispose()}
[string[]]$tickers=@($agg.Keys);[Array]::Sort($tickers,[StringComparer]::Ordinal);if($tickers.Count-ne892){throw "COUNT_$($tickers.Count)"}
# Governed boundary gate: prior durable/reconstructed #611-#620 must still match exactly.
$anchors=@(
'611|PANI|1187480|1187806|327|09:00:00|16:13:00','612|PANR|1186153|1186257|105|09:00:00|16:12:00','613|PANS|1186894|1186928|35|09:00:00|16:11:00','614|PART|1193466|1193534|69|09:04:00|16:00:00','615|PBID|1196074|1196156|83|09:00:00|16:13:00','616|PBSA|1197587|1197693|107|09:00:00|16:04:00','617|PCAR|1197333|1197334|2|10:09:00|13:31:00','618|PDES|1197394|1197394|1|09:01:00|09:01:00','619|PDPP|1199854|1199968|115|09:00:00|16:09:00','620|PEGE|1201696|1201764|69|09:00:00|15:49:00')
$anchorProof=@();foreach($s in $anchors){$x=$s.Split('|');$i=[int]$x[0];$t=$tickers[$i-1];$a=$agg[$t];$ft=$a.first_datetime.Substring($a.first_datetime.Length-8);$lt=$a.last_datetime.Substring($a.last_datetime.Length-8);if($t-ne$x[1]-or$a.first-ne[int]$x[2]-or$a.last-ne[int]$x[3]-or$a.count-ne[int]$x[4]-or$ft-ne$x[5]-or$lt-ne$x[6]){throw "ANCHOR_$i"};$anchorProof+=[pscustomobject]@{index=$i;ticker=$t;status='PASS'}}
$specs=@();for($i=621;$i-le630;$i++){$t=$tickers[$i-1];$a=$agg[$t];$specs+=[pscustomobject][ordered]@{index=$i;ticker=$t;first=[int]$a.first;last=[int]$a.last;count=[int]$a.count;first_time=$a.first_datetime.Substring($a.first_datetime.Length-8);last_time=$a.last_datetime.Substring($a.last_datetime.Length-8);bundle_line=($i-552)}}
$specs|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $out 'MANIFEST_NEXT_621_630.json') -Encoding UTF8
# Pass 2: extract every actual source-supported row for only the governed next block.
$map=@{};foreach($s in $specs){$map[$s.ticker]=New-Object System.Collections.Generic.List[object]};$minFirst=($specs|Measure-Object first -Minimum).Minimum;$maxLast=($specs|Measure-Object last -Maximum).Maximum
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576)
try{$hdr2=$sr.ReadLine();$h2=@($hdr2.TrimStart([char]0xFEFF).Split(','));$pl=1;while(-not$sr.EndOfStream){$line=$sr.ReadLine();$pl++;$row=$pl-1;if($row-gt$maxLast){break};if($row-lt$minFirst){continue};foreach($s in $specs){if($row-ge$s.first-and$row-le$s.last){$x=$line|ConvertFrom-Csv -Header $h2;$f=[ordered]@{};foreach($hh in $h2){$f[$hh]=$x.$hh};$map[$s.ticker].Add([pscustomobject]@{source_row=[int]$row;physical_line=[int]$pl;raw_line=$line;fields=$f});break}}}}finally{$sr.Dispose()}
$proof=@();foreach($s in $specs){$a=$map[$s.ticker];if($a.Count-ne$s.count){throw "$($s.ticker)_COUNT"};for($j=0;$j-lt$a.Count;$j++){if($a[$j].source_row-ne($s.first+$j)){throw "$($s.ticker)_ROW"};if($a[$j].fields.RAW_TICKER-ne$s.ticker){throw "$($s.ticker)_TICKER"};if(-not([string]$a[$j].fields.RAW_DATETIME_ISO).StartsWith($date)){throw "$($s.ticker)_DATE"}};$fd=[string]$a[0].fields.RAW_DATETIME_ISO;$ld=[string]$a[$a.Count-1].fields.RAW_DATETIME_ISO;[ordered]@{source_name=[IO.Path]::GetFileName($raw);source_md5=$gm;source_sha256=$gs;ticker=$s.ticker;manifest_index=[int]$s.index;trading_date=$date;semantic_bundle='Raw Des 02-31-2024__SEMANTIC_0004.jsonl';bundle_line_number=[int]$s.bundle_line;source_row_first=[int]$s.first;source_row_last=[int]$s.last;data_rows=[int]$s.count;first_datetime=$fd;last_datetime=$ld;header_line=$hdr2;header_fields=$h2;rows=$a}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $out "$($s.ticker)_20241202_PACKET.json") -Encoding UTF8;$rp=Join-Path $out "$($s.ticker)_20241202_ROWS.jsonl";if(Test-Path $rp){Remove-Item $rp -Force};foreach($rr in $a){($rr|ConvertTo-Json -Depth 6 -Compress)|Add-Content -LiteralPath $rp -Encoding UTF8};$proof+=[pscustomobject]@{index=$s.index;ticker=$s.ticker;trading_date=$date;bundle_line_number=$s.bundle_line;source_row_first=$s.first;source_row_last=$s.last;data_rows=$s.count;first_datetime=$fd;last_datetime=$ld}}
[ordered]@{status='PASS';method='CANONICAL_RAW_FULL_MANIFEST_RECONSTRUCTION_WITH_PRIOR_BLOCK_BOUNDARY_GATE_THEN_EXACT_ROW_EXTRACTION';source_md5=$gm;source_sha256=$gs;trading_date=$date;total_ticker_context_paths=892;anchor_pass_count=10;anchors=$anchorProof;tickers=$proof}|ConvertTo-Json -Depth 7|Set-Content -LiteralPath (Join-Path $out 'CHUNK_PROOF.json') -Encoding UTF8
