$ErrorActionPreference='Stop'
$raw='D:\TRADING SYSTEM\02_CURRENT_HISTORICAL_RAW_DATA_UJI\Raw Des 02-31-2024.csv'
$date='2024-12-02';$md5='b8d42b35c90d2dff8b18ae4e1734523b';$sha='5bddb43f243e3cbb76504ecc38d8b0981e38866b7a4ea3b4557dcbbf3024712c'
if(-not(Test-Path -LiteralPath $raw -PathType Leaf)){throw 'RAW_MISSING'}
if((Get-FileHash $raw -Algorithm MD5).Hash.ToLowerInvariant()-ne$md5-or(Get-FileHash $raw -Algorithm SHA256).Hash.ToLowerInvariant()-ne$sha){throw 'RAW_HASH_MISMATCH'}
$out=Join-Path $PWD 'machine1_next_691_700_20241202_evidence';New-Item -ItemType Directory -Path $out -Force|Out-Null
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576);$agg=@{};$row=0
try{$hdr=$sr.ReadLine();$h=@($hdr.TrimStart([char]0xFEFF).Split(','));$ti=[Array]::IndexOf($h,'RAW_TICKER');$di=[Array]::IndexOf($h,'RAW_DATETIME_ISO');while(-not$sr.EndOfStream){$line=$sr.ReadLine();$row++;$f=$line.Split(',');if($f.Count-le[Math]::Max($ti,$di)){continue};$dt=$f[$di].Trim('"');if(-not$dt.StartsWith($date)){continue};$t=$f[$ti].Trim('"');if(-not$agg.ContainsKey($t)){$agg[$t]=[ordered]@{ticker=$t;first=$row;last=$row;count=1;first_datetime=$dt;last_datetime=$dt}}else{$a=$agg[$t];$a.last=$row;$a.count++;$a.last_datetime=$dt}}}finally{$sr.Dispose()}
[string[]]$tickers=@($agg.Keys);[Array]::Sort($tickers,[StringComparer]::Ordinal);if($tickers.Count-ne892){throw "COUNT_$($tickers.Count)"}
$anchors=@('681|RDTX|1312399|1312400|2','682|REAL|1312473|1312477|5','683|RELF|1312720|1312788|69','684|RELI|1312601|1312603|3','685|RGAS|1314495|1314609|115','686|RICY|1313912|1313953|42','687|RIGS|1316043|1316114|72','688|RISE|1318455|1318511|57','689|RMKE|1319306|1319368|63','690|RMKO|1320019|1320081|63')
$ap=@();foreach($s in $anchors){$x=$s.Split('|');$i=[int]$x[0];$t=$tickers[$i-1];$a=$agg[$t];if($t-ne$x[1]-or$a.first-ne[int]$x[2]-or$a.last-ne[int]$x[3]-or$a.count-ne[int]$x[4]){throw "ANCHOR_$i"};$ap+=[pscustomobject]@{index=$i;ticker=$t;status='PASS'}}
$specs=@();for($i=691;$i-le700;$i++){$t=$tickers[$i-1];$a=$agg[$t];$specs+=[pscustomobject][ordered]@{index=$i;ticker=$t;first=[int]$a.first;last=[int]$a.last;count=[int]$a.count;first_time=$a.first_datetime.Substring($a.first_datetime.Length-8);last_time=$a.last_datetime.Substring($a.last_datetime.Length-8);bundle_line=($i-552)}}
$specs|ConvertTo-Json -Depth 5|Set-Content (Join-Path $out 'MANIFEST_NEXT_691_700.json') -Encoding UTF8
$map=@{};foreach($s in $specs){$map[$s.ticker]=New-Object System.Collections.Generic.List[object]};$min=($specs|Measure-Object first -Minimum).Minimum;$max=($specs|Measure-Object last -Maximum).Maximum
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576);try{$hdr2=$sr.ReadLine();$h2=@($hdr2.TrimStart([char]0xFEFF).Split(','));$r=0;while(-not$sr.EndOfStream){$line=$sr.ReadLine();$r++;if($r-gt$max){break};if($r-lt$min){continue};foreach($s in $specs){if($r-ge$s.first-and$r-le$s.last){$x=$line|ConvertFrom-Csv -Header $h2;$f=[ordered]@{};foreach($hh in $h2){$f[$hh]=$x.$hh};$map[$s.ticker].Add([pscustomobject]@{source_row=$r;raw_line=$line;fields=$f});break}}}}finally{$sr.Dispose()}
$proof=@();foreach($s in $specs){$a=$map[$s.ticker];if($a.Count-ne$s.count){throw "$($s.ticker)_COUNT"};for($j=0;$j-lt$a.Count;$j++){if($a[$j].source_row-ne($s.first+$j)){throw "$($s.ticker)_ROW"};if($a[$j].fields.RAW_TICKER-ne$s.ticker){throw "$($s.ticker)_TICKER"};if(-not([string]$a[$j].fields.RAW_DATETIME_ISO).StartsWith($date)){throw "$($s.ticker)_DATE"}};[ordered]@{source_name=[IO.Path]::GetFileName($raw);source_md5=$md5;source_sha256=$sha;ticker=$s.ticker;manifest_index=$s.index;trading_date=$date;semantic_bundle='Raw Des 02-31-2024__SEMANTIC_0004.jsonl';bundle_line_number=$s.bundle_line;source_row_first=$s.first;source_row_last=$s.last;data_rows=$s.count;first_datetime=$a[0].fields.RAW_DATETIME_ISO;last_datetime=$a[$a.Count-1].fields.RAW_DATETIME_ISO;header_line=$hdr2;header_fields=$h2;rows=$a}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out "$($s.ticker)_20241202_PACKET.json") -Encoding UTF8;$rp=Join-Path $out "$($s.ticker)_20241202_ROWS.jsonl";foreach($rr in $a){($rr|ConvertTo-Json -Depth 6 -Compress)|Add-Content $rp -Encoding UTF8};$proof+=[pscustomobject]@{index=$s.index;ticker=$s.ticker;trading_date=$date;bundle_line_number=$s.bundle_line;source_row_first=$s.first;source_row_last=$s.last;data_rows=$s.count;first_datetime=$a[0].fields.RAW_DATETIME_ISO;last_datetime=$a[$a.Count-1].fields.RAW_DATETIME_ISO}}
[ordered]@{status='PASS';source_md5=$md5;source_sha256=$sha;trading_date=$date;total_ticker_context_paths=892;anchor_pass_count=10;anchors=$ap;tickers=$proof}|ConvertTo-Json -Depth 7|Set-Content (Join-Path $out 'CHUNK_PROOF.json') -Encoding UTF8
