$ErrorActionPreference='Stop'
$raw='D:\TRADING SYSTEM\02_CURRENT_HISTORICAL_RAW_DATA_UJI\Raw Des 02-31-2024.csv'
$date='2024-12-02';$md5='b8d42b35c90d2dff8b18ae4e1734523b';$sha='5bddb43f243e3cbb76504ecc38d8b0981e38866b7a4ea3b4557dcbbf3024712c'
if(-not(Test-Path -LiteralPath $raw -PathType Leaf)){throw 'RAW_MISSING'}
if((Get-FileHash $raw -Algorithm MD5).Hash.ToLowerInvariant()-ne$md5-or(Get-FileHash $raw -Algorithm SHA256).Hash.ToLowerInvariant()-ne$sha){throw 'RAW_HASH_MISMATCH'}
$out=Join-Path $PWD 'machine1_next_701_710_20241202_evidence';New-Item -ItemType Directory -Path $out -Force|Out-Null
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576);$agg=@{};$row=0
try{$hdr=$sr.ReadLine();$h=@($hdr.TrimStart([char]0xFEFF).Split(','));$ti=[Array]::IndexOf($h,'RAW_TICKER');$di=[Array]::IndexOf($h,'RAW_DATETIME_ISO');if($ti-lt0-or$di-lt0){throw 'HEADER'};while(-not$sr.EndOfStream){$line=$sr.ReadLine();$row++;$f=$line.Split(',');if($f.Count-le[Math]::Max($ti,$di)){continue};$dt=$f[$di].Trim('"');if(-not$dt.StartsWith($date)){continue};$t=$f[$ti].Trim('"');if(-not$agg.ContainsKey($t)){$agg[$t]=[ordered]@{ticker=$t;first=$row;last=$row;count=1;first_datetime=$dt;last_datetime=$dt}}else{$a=$agg[$t];$a.last=$row;$a.count++;$a.last_datetime=$dt}}}finally{$sr.Dispose()}
[string[]]$tickers=@($agg.Keys);[Array]::Sort($tickers,[StringComparer]::Ordinal);if($tickers.Count-ne892){throw "COUNT_$($tickers.Count)"}
$anchors=@('691|RODA|1321076|1321079|4|09:55:00|16:00:00','692|RONY|1321146|1321151|6|09:55:00|16:05:00','693|ROTI|1321325|1321375|51|09:00:00|16:00:00','694|RSCH|1322436|1322461|26|09:00:00|16:00:00','695|RSGK|1323049|1323060|12|09:11:00|15:35:00','696|RUIS|1324001|1324041|41|09:03:00|16:00:00','697|RUNS|1323584|1323591|8|09:00:00|16:00:00','698|SAFE|1324975|1325001|27|09:13:00|15:42:00','699|SAGE|1324844|1324850|7|09:55:00|16:13:00','700|SAME|1326400|1326464|65|09:12:00|16:01:00')
$ap=@();foreach($s in $anchors){$x=$s.Split('|');$i=[int]$x[0];$t=$tickers[$i-1];$a=$agg[$t];$ft=$a.first_datetime.Substring($a.first_datetime.Length-8);$lt=$a.last_datetime.Substring($a.last_datetime.Length-8);if($t-ne$x[1]-or$a.first-ne[int]$x[2]-or$a.last-ne[int]$x[3]-or$a.count-ne[int]$x[4]-or$ft-ne$x[5]-or$lt-ne$x[6]){throw "ANCHOR_$i"};$ap+=[pscustomobject]@{index=$i;ticker=$t;status='PASS'}}
$specs=@();for($i=701;$i-le710;$i++){$t=$tickers[$i-1];$a=$agg[$t];$specs+=[pscustomobject][ordered]@{index=$i;ticker=$t;first=[int]$a.first;last=[int]$a.last;count=[int]$a.count;first_time=$a.first_datetime.Substring($a.first_datetime.Length-8);last_time=$a.last_datetime.Substring($a.last_datetime.Length-8);bundle_line=($i-552)}}
$specs|ConvertTo-Json -Depth 5|Set-Content (Join-Path $out 'MANIFEST_NEXT_701_710.json') -Encoding UTF8
$map=@{};foreach($s in $specs){$map[$s.ticker]=New-Object System.Collections.Generic.List[object]};$min=($specs|Measure-Object first -Minimum).Minimum;$max=($specs|Measure-Object last -Maximum).Maximum
$sr=New-Object IO.StreamReader($raw,[Text.Encoding]::UTF8,$true,1048576);try{$hdr2=$sr.ReadLine();$h2=@($hdr2.TrimStart([char]0xFEFF).Split(','));$r=0;while(-not$sr.EndOfStream){$line=$sr.ReadLine();$r++;if($r-gt$max){break};if($r-lt$min){continue};foreach($s in $specs){if($r-ge$s.first-and$r-le$s.last){$x=$line|ConvertFrom-Csv -Header $h2;$f=[ordered]@{};foreach($hh in $h2){$f[$hh]=$x.$hh};$map[$s.ticker].Add([pscustomobject]@{source_row=$r;raw_line=$line;fields=$f});break}}}}finally{$sr.Dispose()}
$proof=@();foreach($s in $specs){$a=$map[$s.ticker];if($a.Count-ne$s.count){throw "$($s.ticker)_COUNT"};for($j=0;$j-lt$a.Count;$j++){if($a[$j].source_row-ne($s.first+$j)){throw "$($s.ticker)_ROW"};if($a[$j].fields.RAW_TICKER-ne$s.ticker){throw "$($s.ticker)_TICKER"};if(-not([string]$a[$j].fields.RAW_DATETIME_ISO).StartsWith($date)){throw "$($s.ticker)_DATE"}};[ordered]@{source_name=[IO.Path]::GetFileName($raw);source_md5=$md5;source_sha256=$sha;ticker=$s.ticker;manifest_index=$s.index;trading_date=$date;semantic_bundle='Raw Des 02-31-2024__SEMANTIC_0004.jsonl';bundle_line_number=$s.bundle_line;source_row_first=$s.first;source_row_last=$s.last;data_rows=$s.count;first_datetime=$a[0].fields.RAW_DATETIME_ISO;last_datetime=$a[$a.Count-1].fields.RAW_DATETIME_ISO;header_line=$hdr2;header_fields=$h2;rows=$a}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out "$($s.ticker)_20241202_PACKET.json") -Encoding UTF8;$rp=Join-Path $out "$($s.ticker)_20241202_ROWS.jsonl";if(Test-Path $rp){Remove-Item $rp -Force};foreach($rr in $a){($rr|ConvertTo-Json -Depth 6 -Compress)|Add-Content $rp -Encoding UTF8};$proof+=[pscustomobject]@{index=$s.index;ticker=$s.ticker;trading_date=$date;bundle_line_number=$s.bundle_line;source_row_first=$s.first;source_row_last=$s.last;data_rows=$s.count;first_datetime=$a[0].fields.RAW_DATETIME_ISO;last_datetime=$a[$a.Count-1].fields.RAW_DATETIME_ISO}}
[ordered]@{status='PASS';method='CANONICAL_RAW_FULL_MANIFEST_RECONSTRUCTION_WITH_PRIOR_BLOCK_BOUNDARY_GATE_THEN_EXACT_ROW_EXTRACTION';source_md5=$md5;source_sha256=$sha;trading_date=$date;total_ticker_context_paths=892;anchor_pass_count=10;anchors=$ap;tickers=$proof}|ConvertTo-Json -Depth 7|Set-Content (Join-Path $out 'CHUNK_PROOF.json') -Encoding UTF8
